title: Austin Spivey
author_email: aps9721@uncw.edu
description: Austin Spivey is about to graduate from UNCW with a degree in Business. He knows some stuff and is looking for the perfect place to use that stuff.
baseurl: blog
url: http://spiv.me/
theme: jekyll-theme-cayman
